"""Add TranslationMemory model

Revision ID: 951d4db40266
Revises: e060b8cefeb8
Create Date: 2026-09-01 22:48:36.702727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951d4db40266'
down_revision: Union[str, Sequence[str], None] = 'e060b8cefeb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_memories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_memories_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_memories_source_language'), ['source_language'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_memories_target_language'), ['target_language'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_memories_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_memories_user_id'))
        batch_op.drop_index(batch_op.f('ix_translation_memories_target_language'))
        batch_op.drop_index(batch_op.f('ix_translation_memories_source_language'))
        batch_op.drop_index(batch_op.f('ix_translation_memories_project_id'))

    op.drop_table('translation_memories')
    # ### end Alembic commands ###
